export const menFinalPagesMatrix = [
  {
    title: 'Мужские сорочки',
    route: '/services/custom-tailoring/men/shirts',
    folder: 'men-shirts',
    baseName: 'сорочка мужская',
    priceFrom: 27000,
    angle: 'воротник, манжеты, планка, посадка по плечу и груди',
    galleryImage: '/images/custom-tailoring/men/shirts.png',
  },
  {
    title: 'Классические брюки',
    route: '/services/custom-tailoring/men/classic-trousers',
    folder: 'men-classic-trousers',
    baseName: 'классические брюки',
    priceFrom: 30000,
    angle: 'посадка по талии, линия шага, стрелки, карманы и длина',
    galleryImage: '/images/custom-tailoring/men/classic-trousers.png',
  },
  {
    title: 'Пиджаки Casual',
    route: '/services/custom-tailoring/men/casual-jackets',
    folder: 'men-casual-jackets',
    baseName: 'пиджак мужской кежуал',
    priceFrom: 65000,
    angle: 'мягкая конструкция, плечо, лацканы, подкладка и посадка',
    galleryImage: '/images/custom-tailoring/men/casual-jacket.png',
  },
  {
    title: 'Пиджаки классические',
    route: '/services/custom-tailoring/men/bespoke-jackets',
    folder: 'men-bespoke-jackets',
    baseName: 'пиджак мужской классический',
    priceFrom: 120000,
    angle: 'классическая конструкция, ручная работа, плечо, лацканы и посадка',
    galleryImage: '/images/custom-tailoring/men/classic-jacket.png',
  },
  {
    title: 'Пальто',
    route: '/services/custom-tailoring/men/coats',
    folder: 'men-coats',
    baseName: 'пальто',
    priceFrom: 52000,
    angle: 'плечо, длина, воротник, подкладка и пальтовые ткани',
    galleryImage: '/images/custom-tailoring/men/coat.png',
  },
  {
    title: 'Куртки',
    route: '/services/custom-tailoring/men/jackets',
    folder: 'men-jackets',
    baseName: 'куртка без подкладки',
    priceFrom: 40000,
    angle: 'объём, молния, карманы, капюшон и функциональная посадка',
    galleryImage: '/images/custom-tailoring/men/jacket-unlined.png',
  },
  {
    title: 'Бомберы',
    route: '/services/custom-tailoring/men/bombers',
    folder: 'men-bombers',
    baseName: 'бомбер мужской без подкладки',
    priceFrom: 35000,
    angle: 'манжеты, молния, эластичный низ, посадка и материал',
    galleryImage: '/images/custom-tailoring/men/bomber.png',
  },
  {
    title: 'Парки',
    route: '/services/custom-tailoring/men/parkas',
    folder: 'men-parkas',
    baseName: 'парка без подкладки',
    priceFrom: 48000,
    angle: 'капюшон, карманы, кулиски, длина и защитные ткани',
    galleryImage: '/images/custom-tailoring/men/parka.png',
  },
  {
    title: 'Пуховики',
    route: '/services/custom-tailoring/men/down-jackets',
    folder: 'men-down-jackets',
    baseName: 'пуховик короткий',
    priceFrom: 65000,
    angle: 'утепление, стёжка, объём, капюшон и фурнитура',
    galleryImage: '/images/custom-tailoring/men/down-jacket-short.png',
  },
  {
    title: 'Дубленки',
    route: '/services/custom-tailoring/men/shearling-coats',
    folder: 'men-shearling-coats',
    baseName: 'дубленка короткая',
    priceFrom: 80000,
    angle: 'кожа, мех, обработка края, посадка и фурнитура',
    galleryImage: '/images/custom-tailoring/men/shearling-coat.png',
  },
  {
    title: 'Худи',
    route: '/services/custom-tailoring/men/hoodies',
    folder: 'men-hoodies',
    baseName: 'худи с капюшеном',
    priceFrom: 20000,
    angle: 'капюшон, карман, манжеты, объём и плотность трикотажа',
    galleryImage: '/images/custom-tailoring/men/hoodie.png',
  },
  {
    title: 'Свитшоты',
    route: '/services/custom-tailoring/men/sweatshirts',
    folder: 'men-sweatshirts',
    baseName: 'свитшот трикотажный',
    priceFrom: 14000,
    angle: 'горловина, манжеты, объём, длина и трикотаж',
    galleryImage: '/images/custom-tailoring/men/sweatshirt.png',
  },
  {
    title: 'Футболки',
    route: '/services/custom-tailoring/men/t-shirts',
    folder: 'men-t-shirts',
    baseName: 'футболка',
    priceFrom: 8000,
    angle: 'горловина, рукав, длина, посадка и трикотаж',
  },
];

export const menFinalPagesGenerationPlan = {
  templateFolder: 'women-jackets',
  templateRoute: '/services/custom-tailoring/women/jackets',
  routeMounting: 'Use the same final service page registry as women pages.',
  requiredChecks: [
    'node --check server.js',
    'node --check for every generated assets/service-page.js',
    'JSON.parse for every generated page-data.json',
    'JSON.parse every application/ld+json script in every generated index.html',
    'No stale women/dress template words in generated men pages',
    'curl/head every final route returns 200',
    'curl/head CSS and JS assets for every generated folder returns 200',
  ],
};
