export const womenFinalPagesMatrix = [
  {
    group: 'Платья',
    pages: [
      {
        title: 'Платья-футляры',
        route: '/services/custom-tailoring/women/dresses/sheath',
        folder: 'sheath-dresses',
        baseName: 'платье футляр без рукава',
        priceFrom: 25000,
        status: 'done',
        angle: 'прилегающий силуэт, точная посадка по груди, талии и бедрам',
      },
      {
        title: 'Прямые платья',
        route: '/services/custom-tailoring/women/dresses/straight',
        folder: 'straight-dresses',
        baseName: 'платье прямое с рукавом',
        priceFrom: 30000,
        status: 'done',
        angle: 'свободный прямой силуэт, рукава, комфортная посадка',
        galleryImage: '/images/custom-tailoring/women/straight-dress-table.png',
      },
      {
        title: 'Отрезные платья',
        route: '/services/custom-tailoring/women/dresses/cut-off-waist',
        folder: 'cut-off-waist-dresses',
        baseName: 'платье с отрезной талией',
        priceFrom: 35000,
        status: 'done',
        angle: 'отдельная посадка лифа и юбки, линия талии, пропорции',
        galleryImage: '/images/custom-tailoring/women/cut-off-waist-dress.png',
      },
      {
        title: 'Вечерние платья',
        route: '/services/custom-tailoring/women/dresses/evening',
        folder: 'evening-dresses',
        baseName: 'платье вечернее(свадебное)',
        priceFrom: 80000,
        status: 'done',
        angle: 'образ для события, сложные ткани, декор, посадка под фигуру',
        galleryImage: '/images/custom-tailoring/women/evening-dress.png',
      },
      {
        title: 'Платья по фото',
        route: '/services/custom-tailoring/women/dresses/from-photo',
        folder: 'dresses-from-photo',
        baseName: 'платье футляр без рукава',
        priceFrom: 25000,
        status: 'todo',
        angle: 'адаптация фото под фигуру, материал и сценарий носки',
        galleryImage: '/images/custom-tailoring/women/dress-from-photo.png',
      },
      {
        title: 'Платья по референсу бренда',
        route: '/services/custom-tailoring/women/dresses/brand-reference',
        folder: 'brand-reference-dresses',
        baseName: 'платье футляр без рукава',
        priceFrom: 25000,
        status: 'todo',
        angle: 'референс бренда как направление, индивидуальная посадка и материалы',
        galleryImage: '/images/custom-tailoring/women/brand-reference-dress.png',
      },
    ],
  },
  {
    group: 'Юбки',
    pages: [
      {
        title: 'Прямые юбки',
        route: '/services/custom-tailoring/women/skirts/straight',
        folder: 'straight-skirts',
        baseName: 'юбка прямая до колена',
        priceFrom: 15000,
        status: 'todo',
        angle: 'чистая посадка по талии и бедрам, длина, шлица, подкладка',
        galleryImage: '/images/custom-tailoring/women/straight-skirt.png',
      },
      {
        title: 'Юбки по косой',
        route: '/services/custom-tailoring/women/skirts/bias-cut',
        folder: 'bias-cut-skirts',
        baseName: 'юбка по косой',
        priceFrom: 20000,
        status: 'todo',
        angle: 'пластика ткани, косой крой, мягкая линия и посадка',
        galleryImage: '/images/custom-tailoring/women/bias-cut-skirt.png',
      },
      {
        title: 'Мини-юбки',
        route: '/services/custom-tailoring/women/skirts/mini',
        folder: 'mini-skirts',
        baseName: 'юбка прямая до колена',
        priceFrom: 15000,
        status: 'todo',
        angle: 'короткая длина, посадка по талии и бедрам, пропорции',
      },
      {
        title: 'Макси-юбки',
        route: '/services/custom-tailoring/women/skirts/maxi',
        folder: 'maxi-skirts',
        baseName: 'юбка по косой',
        priceFrom: 20000,
        status: 'todo',
        angle: 'длина макси, пластика ткани, движение и баланс силуэта',
        galleryImage: '/images/custom-tailoring/women/maxi-skirt.png',
      },
      {
        title: 'Юбки по фото',
        route: '/services/custom-tailoring/women/skirts/from-photo',
        folder: 'skirts-from-photo',
        baseName: 'юбка прямая до колена',
        priceFrom: 15000,
        status: 'todo',
        angle: 'адаптация фото юбки под фигуру, ткань и длину',
      },
    ],
  },
  {
    group: 'Женские категории',
    pages: [
      {
        title: 'Топы',
        route: '/services/custom-tailoring/women/tops',
        folder: 'women-tops',
        baseName: 'топ',
        priceFrom: 14000,
        status: 'todo',
        angle: 'мягкая посадка, вырез, бретели или рукав, ткань и обработка края',
        galleryImage: '/images/custom-tailoring/women/top.png',
      },
      {
        title: 'Брюки',
        route: '/services/custom-tailoring/women/trousers',
        folder: 'women-trousers',
        baseName: 'брюки женские два кармана',
        priceFrom: 26000,
        status: 'todo',
        angle: 'посадка по талии и бедрам, длина, карманы, силуэт',
        galleryImage: '/images/custom-tailoring/women/trousers.png',
      },
      {
        title: 'Жакеты',
        route: '/services/custom-tailoring/women/jackets',
        folder: 'women-jackets',
        baseName: 'жакет',
        priceFrom: 48000,
        status: 'todo',
        angle: 'плечо, посадка, лацканы, подкладка, конструкция',
      },
      {
        title: 'Корсеты',
        route: '/services/custom-tailoring/women/corsets',
        folder: 'women-corsets',
        baseName: 'корсет',
        priceFrom: 50000,
        status: 'todo',
        angle: 'посадка по фигуре, поддержка, чашки, косточки, застежка',
      },
      {
        title: 'Полукорсеты',
        route: '/services/custom-tailoring/women/half-corsets',
        folder: 'women-half-corsets',
        baseName: 'полукорсет (бельевой)',
        priceFrom: 35000,
        status: 'todo',
        angle: 'деликатная посадка, бельевая основа, форма и поддержка',
      },
      {
        title: 'Блузы',
        route: '/services/custom-tailoring/women/blouses',
        folder: 'women-blouses',
        baseName: 'блуза',
        priceFrom: 27000,
        status: 'todo',
        angle: 'ткань, рукав, воротник, застежка, мягкая посадка',
        galleryImage: '/images/custom-tailoring/women/blouse.png',
      },
      {
        title: 'Рубашки',
        route: '/services/custom-tailoring/women/shirts',
        folder: 'women-shirts',
        baseName: 'сорочка (рубашка)',
        priceFrom: 25000,
        status: 'todo',
        angle: 'воротник, манжеты, планка, посадка по плечу и груди',
      },
      {
        title: 'Пальто',
        route: '/services/custom-tailoring/women/coats',
        folder: 'women-coats',
        baseName: 'пальто',
        priceFrom: 52000,
        status: 'todo',
        angle: 'верхняя одежда, подкладка, плечо, длина, воротник',
      },
      {
        title: 'Плащи',
        route: '/services/custom-tailoring/women/trench-coats',
        folder: 'women-trench-coats',
        baseName: 'плащ',
        priceFrom: 45000,
        status: 'todo',
        angle: 'плащевые ткани, пояс, воротник, застежка, защита от погоды',
        galleryImage: '/images/custom-tailoring/women/trench-coat.png',
      },
      {
        title: 'Куртки',
        route: '/services/custom-tailoring/women/jackets-outerwear',
        folder: 'women-outerwear-jackets',
        baseName: 'куртка без подкладки',
        priceFrom: 40000,
        status: 'todo',
        angle: 'короткая верхняя одежда, молния, карманы, капюшон, подкладка',
        galleryImage: '/images/custom-tailoring/women/jacket-outerwear.png',
      },
      {
        title: 'Бомберы',
        route: '/services/custom-tailoring/women/bombers',
        folder: 'women-bombers',
        baseName: 'бомбер мужской без подкладки',
        priceFrom: 35000,
        status: 'todo',
        angle: 'эластичный низ, манжеты, молния, посадка и материал',
        galleryImage: '/images/custom-tailoring/women/bomber.png',
      },
      {
        title: 'Парки',
        route: '/services/custom-tailoring/women/parkas',
        folder: 'women-parkas',
        baseName: 'парка без подкладки',
        priceFrom: 48000,
        status: 'todo',
        angle: 'утилитарная верхняя одежда, капюшон, карманы, кулиски',
        galleryImage: '/images/custom-tailoring/women/parka.png',
      },
      {
        title: 'Пуховики',
        route: '/services/custom-tailoring/women/down-jackets',
        folder: 'women-down-jackets',
        baseName: 'пуховик короткий',
        priceFrom: 65000,
        status: 'todo',
        angle: 'утепление, стежка, длина, объем, капюшон и фурнитура',
        galleryImage: '/images/custom-tailoring/women/down-jacket.png',
      },
      {
        title: 'Дубленки',
        route: '/services/custom-tailoring/women/shearling-coats',
        folder: 'women-shearling-coats',
        baseName: 'дубленка короткая',
        priceFrom: 80000,
        status: 'todo',
        angle: 'кожа и мех, посадка, длина, фурнитура, обработка края',
      },
      {
        title: 'Жилеты',
        route: '/services/custom-tailoring/women/vests',
        folder: 'women-vests',
        baseName: 'жилет',
        priceFrom: 24000,
        status: 'todo',
        angle: 'посадка, пройма, застежка, подкладка, многослойность',
      },
      {
        title: 'Лонгсливы',
        route: '/services/custom-tailoring/women/long-sleeves',
        folder: 'women-long-sleeves',
        baseName: 'лонгслив трикотажный',
        priceFrom: 14000,
        status: 'todo',
        angle: 'трикотаж, рукав, горловина, посадка и растяжимость',
        galleryImage: '/images/custom-tailoring/women/long-sleeve.png',
      },
      {
        title: 'Худи',
        route: '/services/custom-tailoring/women/hoodies',
        folder: 'women-hoodies',
        baseName: 'худи с капюшеном',
        priceFrom: 20000,
        status: 'todo',
        angle: 'капюшон, карман, манжеты, посадка и плотность трикотажа',
      },
      {
        title: 'Свитшоты',
        route: '/services/custom-tailoring/women/sweatshirts',
        folder: 'women-sweatshirts',
        baseName: 'свитшот трикотажный',
        priceFrom: 14000,
        status: 'todo',
        angle: 'трикотаж, манжеты, горловина, посадка и объем',
        galleryImage: '/images/custom-tailoring/women/sweatshirt-full.png',
      },
      {
        title: 'Футболки',
        route: '/services/custom-tailoring/women/t-shirts',
        folder: 'women-t-shirts',
        baseName: 'футболка',
        priceFrom: 8000,
        status: 'todo',
        angle: 'трикотаж, горловина, длина, рукав и посадка',
        galleryImage: '/images/custom-tailoring/women/t-shirt.png',
      },
    ],
  },
];

export const womenFinalPagesGenerationPlan = {
  templateFolder: 'cut-off-waist-dresses',
  templateRoute: '/services/custom-tailoring/women/dresses/cut-off-waist',
  routeMounting: 'Use a single FINAL_SERVICE_PAGES array in server.js instead of one constant per page.',
  requiredChecks: [
    'node --check server.js',
    'node --check for every generated assets/service-page.js',
    'JSON.parse for every generated page-data.json',
    'JSON.parse every application/ld+json script in every generated index.html',
    'No stale template words in generated pages',
    'curl -I every final route returns 200',
    'curl -I CSS and JS assets for every generated folder returns 200',
    '/api/service-menu contains only visible service skeleton items',
  ],
};
